### ISSUE TITLE
When selecting a theme, the Live Preview button doesn't work

### ISSUE THREAD

**Issue by a-support** [puikinsh/tyche#17]
Downloaded Tyche template for Wordpress on Colorlib, (link: https://colorlib.com/wp/themes/tyche/ )
Installed it into my WordPress
Then i goes to Theme, thumbnail of that template still show
But when i click on “Activate” or “Live preview” button. It will direct to nothing page.|

https://colorlib.com/wp/forums/topic/tyche-template-displays-nothing-when-i-click-on-activatelive-preview-button/

**Comment by cristeacosmin** [comment]
This issue can't be caused by the theme. If the theme is not activated, WordPress does not require/include its files. It only grabs the screenshot and reads the style.css ( for description/tags/etc ).

**Comment by a-support** [comment]
Hello,

This issue may be related to an outdated version of WordPress our the server settings used by the hosting provider.
