### ISSUE TITLE
Demo page is not showing correctly

### ISSUE THREAD

**Issue by MohiuddinSumon** [puikinsh/tyche#18]
HI , I'm seeing errors like [http://imgur.com/a/9XiD7](this).
also account , my cart and search should go into the navigation box. 
Mobile view is not good also if user has a small screen device 
Thanks

**Comment by angelz12** [comment]
this will help you download this file and overwrite it
 http://rgho.st/65tW5vLCK
replace it in the inc/libraries/class-tyche-frontpage.php

**Comment by a-support** [comment]
Hello @mpmohi ,

You need to ensure that you have installed all the bundled plugins that came with the theme, you can install them via Appearance > Install plugins.

Cheers

**Comment by cristianraiber** [comment]
Closing as this is not an actual theme bug.
