### ISSUE TITLE
"Loading" constantly appears when using Google Adsense

### ISSUE THREAD

**Issue by jabarihunt** [puikinsh/tyche#21]
As stated in the title, a bar with the words "Loading" constantly appears on top of the banner ad that is loaded by Google AdSense.  It stays even after the banner has loaded.

It doesn't appear when using a static image.

 I'm using version 1.07 of the theme.

**Comment by cristianraiber** [comment]
@jabarihunt - could you please try pasting only the `<ins>` part of the AdSense code? It's supposed to be LazyLoaded for performance improvements.

**Comment by jabarihunt** [comment]
Now the "Loading" notice stays, but the banner doesn't display.

**Comment by cristianraiber** [comment]
Could I please have your site's URL ?

**Comment by jabarihunt** [comment]
Give me a minute to re-activate that feature, but it is
https://www.obsidiandefense.com

UPDATE: It's active now...

**Comment by cristianraiber** [comment]
I'm not seeing the banner's HTML code in the theme's source files. Are you sure it's pasted in properly?

**Comment by jabarihunt** [comment]
Sorry, try it now...
