### ISSUE TITLE
some components do not appear :/

### ISSUE THREAD

**Issue by abdurrahmanmert** [puikinsh/tyche#22]
Content Widget Area #2 A
Content Widget Area #2 B
Content Widget Area #2 C

Content Widget Area #4 A
Content Widget Area #4 B

Shop Sidebar

![pwajma](https://user-images.githubusercontent.com/30554351/29325844-e518885e-81f1-11e7-81e6-22d2094cf84a.png)

**Comment by angelz12** [comment]
this will help you download this file and overwrite it
http://rgho.st/65tW5vLCK
replace it in the inc/libraries/class-tyche-frontpage.php

**Comment by cristeacosmin** [comment]
@abdurrahmanmert @angelz12 Let me know if the issue persists in the new version!

**Comment by LuciahAnnah** [comment]
@angelz12  @c0sm1n87  
Hello I download this file but nothing changed and other wise I have others bugs in the home page :/ 
Can you help me ? Please.
![capture d ecran 2018-08-19 a 18 35 53](https://user-images.githubusercontent.com/42518788/44310929-cfd96c00-a3de-11e8-8f09-26bf17bb9e8a.png)

**Comment by cristianraiber** [comment]
Will close this once 1.1.1 gets pushed into the public repository.
