### ISSUE TITLE
Post Author Title Displays Username Rather Than "Display name publicly as" Name

### ISSUE THREAD

**Issue by jabarihunt** [puikinsh/tyche#24]
As the title says, the post author (at the top of a post) should display the "Display name publicly as" name rather than the username.  Screenshot below...

![username_screenshot](https://user-images.githubusercontent.com/2807764/29399154-ae1b59d8-82ed-11e7-9867-46ad1e51b46f.png)

...the author name should be "Jabari Hunt".  FYI - It displays the correct name in the Author Info at the bottom of the post.

**Comment by cristeacosmin** [comment]
@jabarihunt let me know if this fixed your issue.

**Comment by jabarihunt** [comment]
@c0sm1n87 I apologize for the _LATE_ reply!  Yes, it fixed the issue, I'm closing this issue...
