### ISSUE TITLE
Tyche products widget problem: Variable products are being added to the cart

### ISSUE THREAD

**Issue by csandreas1** [puikinsh/tyche#31]
Variable products are being added to the card instead of navigating to the product page when i press the select options button. The bug  is under **tyche products widget**

**Comment by cristianraiber** [comment]
Marking this as closed. Tested, it's not happening.

**Comment by csandreas1** [comment]
are you a good "tester"? Check in [this website](https://frixsample.mpoliasma.top) homepage and i am pretty sure that you will see the problem there if you click the "select options"

**Comment by csandreas1** [comment]
also thanks for the fast reply (18 days)
