### ISSUE TITLE
Categorys with 3 subs* Dont work?

### ISSUE THREAD

**Issue by angelz12** [puikinsh/tyche#33]
Hello dear Support Team,

i got a little problem on my site i need 3 subcategorys but the theme dont show me the last one where i can enable this watch my screenshot than woocommerce allow this!

https://cdn.colorlib.com/wp/wp-content/uploads/sites/2/test-1.jpg

**Comment by cristeacosmin** [comment]
@angelz12 hello, I-ve increased the depth of the menu. Let me know if it's ok!

**Comment by a-support** [comment]
Hello @c0sm1n87 

The menu now allows for more submenu items to be displayed.

**Comment by cristianraiber** [comment]
Closing as this doesn't seem to be an issue anymore.
