### ISSUE TITLE
 Tyche update for woocommerce Version 3

### ISSUE THREAD

**Issue by a-support** [puikinsh/tyche#43]
tyche/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.3.0,
tyche/woocommerce/global/sidebar.php,
tyche/woocommerce/loop/add-to-cart.php version 3.0.0 is out of date. The core version is 3.3.0,
tyche/woocommerce/single-product/add-to-cart/external.php,
tyche/woocommerce/single-product/add-to-cart/grouped.php version 3.0.7 is out of date. The core version is 3.3.0,
tyche/woocommerce/single-product/add-to-cart/simple.php,
tyche/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php,
tyche/woocommerce/single-product/tabs/tabs.php,
tyche/woocommerce/single-product.php

Discussion: https://colorlib.com/wp/forums/topic/tyche-update-for-woocommerce-version-3/

**Comment by jabarihunt** [comment]
A guide: https://docs.woocommerce.com/document/fix-outdated-templates-woocommerce/

I'm tied up this weekend, but I'll update them and create a pull request on Monday...

**Comment by giucu91** [comment]
Duplicate #47
