### ISSUE TITLE
Issues with the latest woocommerce update

### ISSUE THREAD

**Issue by csandreas1** [puikinsh/tyche#44]
https://wordpress.org/support/topic/wc-3-3-issues-with-categories-displaying-in-shop/

> 
There is a known issue on some themes that override WooCommerce template files (Flatsome, Genesis theme with Genesis Connect, potentially others).

When using these themes with WC 3.3, product categories are displayed in the shop as if you had chosen the “Show categories & products” display setting regardless of what display setting is selected.

This is due to a behavior change in the way the woocommerce_product_subcategories function behaves and template file changes in 3.3. We will have a fix for this issue on legacy themes or themes that aren’t being actively updated in WC 3.3.1.

If possible, theme developers should update their themes to use the latest versions of the WooCommerce templates. You can see what template files need to be updated in the release post on the developer blog: https://woocommerce.wordpress.com/2018/01/30/woocommerce-3-3-has-been-released/ (Specifically the archive-product.php template)
>

**Comment by giucu91** [comment]
Duplicate #45
