### ISSUE TITLE
Out of the stock item is displayed on the front page carousel

### ISSUE THREAD

**Issue by nodarik** [puikinsh/tyche#46]
Even if the  WooCommerce > Settings > Products > Inventory and check “Hide out of stock items from the catalog” is enabled to hide out of stock items product still appears in the carousel

steps to replicate:
put one of the product in out of the stock state,
the product is still appearing in the carousel

A ticket where it was reported:
https://colorlib.com/wp/forums/topic/out-of-stock-items-on-first-page-need-help/

**Comment by a-support** [comment]
The out of stock products still appear in the product carousel widget.

**Comment by cristianraiber** [comment]
@giucu91 - please take a look at this

**Comment by cristianraiber** [comment]
@nodarik - can you please look at this and let us know?
