### ISSUE TITLE
Slider text display on mobile devices

### ISSUE THREAD

**Issue by nodarik** [puikinsh/tyche#56]
By default slider text is hidden, this code can fix the problem:

@media (max-width: 767px){
.main-slider .hero-caption.left {
left: 0%;
}
.main-slider .hero-caption {
text-align: center;
}
.main-slider .hero-caption .year {
font-size: 18px;
}
.main-slider .hero-caption .caption {
font-size: 18px;
width: 100%;
}
.main-slider .hero-caption {
display: block !important;
}
}

**Comment by mahendrapratap4022** [comment]
H @nodarik We have hidden those text in mobile devices intentionally as there is no enough space or area for the same.
But if you want to have text on mobile too then you can create a child theme for that and modify css it there.
