### ISSUE TITLE
Getting started 3 row steps bug

### ISSUE THREAD

**Issue by razvanaldea89** [puikinsh/tyche#57]
![tyche 3 row steps](https://user-images.githubusercontent.com/44024114/63742832-c660ca80-c8a2-11e9-8bfb-bfdb4e836744.PNG)

**Comment by mahendrapratap4022** [comment]
Hi @razvanaldea89 , Please explain the bug there is no bug showing in the screenshot.

**Comment by razvanaldea89** [comment]
hi @mahendrapratap4022 , as in the other theme the bug lies in the positioning of the 3 columns being under each other ( Step 1, Step 2 and Step 3 ).  This was 2 years ago, maybe it is fixed now

**Comment by mahendrapratap4022** [comment]
@razvanaldea89 Thank you for the response it is fixed already in the previous version. Thanks for explaining it clearly.
