### ISSUE TITLE
After installing and activating plugins from TGMPA plugin, clicking link gives 'Sorry, you are not allowed to access this page.'

### ISSUE THREAD

**Issue by razvanaldea89** [puikinsh/tyche#59]
![tyche rights](https://user-images.githubusercontent.com/44024114/63744789-1773bd00-c8a9-11e9-8681-606012ee61d1.PNG)

**Comment by mahendrapratap4022** [comment]
Hi @razvanaldea89, please share to details of the plugin how you installed it or share the screenshot of the plugin page.

you can follow http://tgmpluginactivation.com/configuration/ instructions for the installation.
