### ISSUE TITLE
Problem with content widget Areas 

### ISSUE THREAD

**Issue by Leohayequipo** [puikinsh/tyche#60]
Hi! I have tyche 1.1.4, and i have problem with  content widget Areas, only can use footer and side bar! pleace help!
regard. adjunt pics
![2](https://user-images.githubusercontent.com/54806458/65102591-f121d880-d9a1-11e9-8588-ef824c0ce5d9.PNG)
![1](https://user-images.githubusercontent.com/54806458/65102592-f121d880-d9a1-11e9-84f7-440ea319fd11.PNG)

**Comment by mahendrapratap4022** [comment]
Hi @Leohayequipo , Widgets only show here when it is being used on the page you are customizing. 

Please try to select the home page in `Homepage Settings` like this and check. 

<img width="355" alt="Screenshot 2021-06-21 at 4 26 55 PM" src="https://user-images.githubusercontent.com/33213474/122751611-9f605d80-d2ad-11eb-82b0-bd0d93066cc3.png">
