### ISSUE TITLE
The theme is using outdated Woocommerce files.

### ISSUE THREAD

**Issue by dbarrerap** [puikinsh/tyche#61]
WordPress status page reveals grouped and tabs files use outdated templates.

Tyche version installed is 1.1.4
WooCommerce version is 4.2.0

tyche/woocommerce/archive-product.php,
tyche/woocommerce/global/sidebar.php,
tyche/woocommerce/loop/add-to-cart.php,
tyche/woocommerce/single-product/add-to-cart/external.php,
La version 3.4.0 de tyche/woocommerce/single-product/add-to-cart/grouped.php está obsoleta. La versión del núcleo es la 4.0.0,
tyche/woocommerce/single-product/add-to-cart/simple.php,
tyche/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php,
La version 2.4.0 de tyche/woocommerce/single-product/tabs/tabs.php está obsoleta. La versión del núcleo es la 3.8.0,
tyche/woocommerce/single-product.php

Migrate to a child theme version could be a fix?

**Comment by mahendrapratap4022** [comment]
Hi @dbarrerap  , you can create a child theme if you want to change or update anything in the theme including woocommerce files, that would be a good idea. Currently, we have updated woocommerce template according to our theme requirements it's updated already we just have modified those files so if you want to make more changes you can go with the child theme.
