### ISSUE TITLE
Demo link not functioning

### ISSUE THREAD

**Issue by ifeLight** [puikinsh/tyche#62]
The link to download the demo is not working

[https://colorlibvault-divilabltd.netdna-ssl.com/tychedemo.wordpress.xml](https://colorlibvault-divilabltd.netdna-ssl.com/tychedemo.wordpress.xml)
[https://colorlibvault-divilabltd.netdna-ssl.com/tyche-widgets.wie](https://colorlibvault-divilabltd.netdna-ssl.com/tyche-widgets.wie)

Help Fix. Thanks

**Comment by ifeLight** [comment]
Or rather attach the files to the github repository or a seperate branch

**Comment by ifeLight** [comment]
> The link to download the demo is not working
> 
> https://colorlibvault-divilabltd.netdna-ssl.com/tychedemo.wordpress.xml
> https://colorlibvault-divilabltd.netdna-ssl.com/tyche-widgets.wie
> 
> Help Fix. Thanks

Or is there anyone with the files

**Comment by ifeLight** [comment]
> The link to download the demo is not working
> 
> https://colorlibvault-divilabltd.netdna-ssl.com/tychedemo.wordpress.xml
> https://colorlibvault-divilabltd.netdna-ssl.com/tyche-widgets.wie
> 
> Help Fix. Thanks

Or is there anyone with the files @cristianraiber @puikinsh @giucu91 @razvanaldea89 @cristeacosmin

**Comment by puikinsh** [comment]
New download links for the theme demo content and widgets:
https://preview.colorlib.com/downloads/tyche-widgets.wie
https://preview.colorlib.com/downloads/tychedemo.wordpress.xml
