### ISSUE TITLE
Template for wordpress: Tyche Failed to import Media files: The remote server returned an unexpected result: Not Found (404)

### ISSUE THREAD

**Issue by nikitarip** [puikinsh/tyche#71]
Hi, I took the file from here https://preview.colorlib.com/downloads/tychedemo.wordpress.xml , but after installing the template does not get up, I did everything as in the video. What to do? Media files are simply not installed, an error..

Failed to import Media files "model-858751_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media Files “girl-1286993_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files “woman-1477091_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "high-heels-1327020_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "shoe-1040802_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "elegance-18594_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media Files "jeans-428614_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "fashion-731827_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "belts-823257_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files “a-neckerchief-1315916_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files “a-neckerchief-1315912_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files “a-neckerchief-1317830_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files “woman-1211442_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files “woman-1211441_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "boy-882334_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files “long-dress-1438140_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "high-heels-1426011_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import “hero " media files: The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "fashion-984044_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media Files "person-1148941_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "fashion-1283863_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "cute-955782_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "cute-955783_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "cute-955785_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files “girl-in-white-dress-1333640_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media Files “key-692199_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files “woman-1484279_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media Files “clothing-964878_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files "stocks-428602_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files “vibrant-641434_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import Media files “down-jackets-1281699_1920": The remote server returned an unexpected result: Not Found (404)
Failed to import “logo " media files: The remote server returned an unexpected result: Not Found (404)
How can I fix this?

**Comment by mahendrapratap4022** [comment]
Hey, Please use this file for now. we will update it on the live server soon.
[tychedemo.wordpress.txt](https://github.com/ColorlibHQ/tyche/files/6999242/tychedemo.wordpress.txt)

Also, Please update txt with XML as the XML file is not supported here so I've changed the file extension.
