### ISSUE TITLE
Missing files with download

### ISSUE THREAD

**Issue by a-support** [puikinsh/tyche#8]
Hello,

When the file is downloaded there are a few missing files that need to be added to make the theme work, it was solved and here is the solution:

https://colorlib.com/wp/forums/topic/missing-files-in-downloaded-theme/

Cheers

**Comment by cristeacosmin** [comment]
Hello,

This repository contains a git sub-module and as such, can not be completely downloaded using the web-interface of GitHub. This is a known limitation of GitHub's own tools. However, cloning this repository via CLI works absolutely fine and will pull all sub-modules as long as you use the proper commands.

I would recommend using github Releases to download the latest version of the theme.

You can find it here (download the tyche.zip file) :
https://github.com/puikinsh/tyche/releases
